name: seven_health
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_qr_bar_scanner: ^1.0.2
  flutter_spinkit: ^4.1.2+1
  dio: ^3.0.9
  giffy_dialog: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/img/

  fonts:
  - family: rubik
    fonts:
      - asset: assets/fonts/Rubik/Rubik-Light.ttf
        weight: 300
      - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        weight: 400
      - asset: assets/fonts/Rubik/Rubik-Medium.ttf
        weight: 500
      - asset: assets/fonts/Rubik/Rubik-Bold.ttf
        weight: 700
      - asset: assets/fonts/Rubik/Rubik-Black.ttf
        weight: 900
 